# Generated by Django 4.2.3 on 2023-09-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0003_conversation_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
    ]
