# Generated by Django 4.2.3 on 2023-09-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0004_conversation_image_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_image_used',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
