# Generated by Django 4.2.3 on 2023-09-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0006_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hook.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'todo', 'created_at')},
            },
        ),
    ]
