# Generated by Django 4.2.3 on 2023-11-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0006_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('phone', 'feedback', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hook.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'todo', 'created_at')},
            },
        ),
    ]
