# Generated by Django 4.2.3 on 2023-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hook', '0007_conversation_last_message_id_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('phone', 'feedback', 'created_at')},
            },
        ),
    ]
